### ISSUE TITLE
Recent presto version may cause NoSuchMethodError 'QueryStatistics.getPeakMemoryBytes()'

### ISSUE THREAD

**Issue by ebyhr** [yahoojapan/presto-audit#5]
I've tried presto-audit on 0.199 SNAPSHOT presto and faced following error.
```
2018-05-07T23:31:19.511+0900	INFO	main	com.facebook.presto.server.PrestoServer	======== SERVER STARTED ========
2018-05-07T23:31:47.411+0900	ERROR	query-execution-0	com.facebook.presto.execution.StateMachine	Error notifying state change listener for finalQueryInfo-20180507_143146_00000_dtb4y
java.lang.NoSuchMethodError: com.facebook.presto.spi.eventlistener.QueryStatistics.getPeakMemoryBytes()J
	at jp.co.yahoo.presto.audit.serializer.SimpleLogSerializer.buildAuditRecord(SimpleLogSerializer.java:56)
	at jp.co.yahoo.presto.audit.serializer.SimpleLogSerializer.serialize(SimpleLogSerializer.java:36)
	at jp.co.yahoo.presto.audit.AuditLogListener.simpleLog(AuditLogListener.java:73)
	at jp.co.yahoo.presto.audit.AuditLogListener.queryCompleted(AuditLogListener.java:67)
	at com.facebook.presto.eventlistener.EventListenerManager.queryCompleted(EventListenerManager.java:91)
	at com.facebook.presto.event.query.QueryMonitor.queryCompletedEvent(QueryMonitor.java:215)
	at com.facebook.presto.execution.SqlQueryManager.lambda$createQuery$3(SqlQueryManager.java:468)
	at com.facebook.presto.execution.QueryStateMachine.lambda$addQueryInfoStateChangeListener$9(QueryStateMachine.java:761)
	at com.facebook.presto.execution.StateMachine.lambda$fireStateChanged$0(StateMachine.java:222)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

This method(`getPeakMemoryBytes`) was separated by this commit, so the presto which version is greater than or equal to 0.193 causes NoSuchMethodError.
https://github.com/prestodb/presto/commit/4e2167118cf8ab15d0379979765236cfa6520df7#diff-dd6206b6edafb9d4a7ccd74cc82352a8L110

**Comment by yuokada** [comment]
Thanks for your report.

Our presto cluster is using 0.192( or under). I don't face with this issue yet.
I have a plan to solve it soon.

**Comment by ebyhr** [comment]
I see. I'll try with latest presto after the commit is merged.

**Comment by yuokada** [comment]
Fixed https://github.com/yahoojapan/presto-audit/commit/76f5dec63285745b9ca512d27ff161c78375aef8
